### ISSUE TITLE
Rehearse every release's upgrade paths before tagging, including users' Node setups

### ISSUE THREAD

**Issue by jerimiah797** [quern-dev/quern#219]
## Why

Every release has turned up a problem with the *move* to the new version, and each was found by a user or by accident:

| Release | Problem | Why nothing caught it |
|---|---|---|
| 0.14.0 | `release/beta` not moved; beta users stranded | the steps are manual, in an order that's easy to get wrong |
| 0.18.0 → 0.18.1 | the beta channel offered a downgrade | nothing checked what each channel resolves to after publishing |
| 0.18.2 → 0.18.3 | the menu bar couldn't start a tarball install (npm not on the GUI PATH) | never started from a GUI-style environment |
| 0.18.3 (caught before tagging) | the tarball's MCP wrapper shipped without its dependencies | the check ran in a directory that happened to have them |
| 0.18.3 | **every update into it crashed** (#212) | nobody updated *from* the previous release |
| 0.18.3 | setup could leave the menu bar stopped (#215) | only seen during a manual test |
| field | Node 20 reported as fine; a GUI client with no Node at all (#214) | setup checked one place, and never the version |

The common thread: **we test the new code, not the move to it.** Updating, first installs, GUI launches and the user's Node setup were only ever tested by users.

### 1. Rehearsal before tagging: `scripts/release-rehearsal.sh <candidate>`

Automated, a few minutes. Each case runs in its own sandbox: its own `HOME` (with the dotfiles the case needs) and `QUERN_STATE_DIR`, stub `osascript`/`open`/`sudo`/`launchctl`/`pkill`/`killall` first on PATH, and a port that isn't 9100.

**Update and install**

| Case | Runs | Must hold |
|---|---|---|
| Git update | previous tag → candidate through a local bare repo, using the **old** updater | exit 0, no traceback, setup ran, `last-update.json` = `updated` with the new version |
| Tarball update | previous published tarball → candidate tarball served locally, using the **old** updater | same |
| Fresh install | `install.sh` → candidate tarball served locally | installs, setup runs, the wrapper works from another directory |
| GUI-style start | `quern start` under `env -i` with launchd's PATH | server healthy on the new version (#193) |
| Menu-bar step | setup with the app "running" and nothing new delivered | app not quit (#215) |

**Node environments (#214).** Each case sets up the sandbox `HOME`'s `.zshenv` / `.zshrc` and the PATH to recreate a real user's arrangement. A Node 20 binary is fetched once from nodejs.org and cached, so "too old" means a real Node 20 that really builds and really fails to run the wrapper, not a stand-in.

| Case | Arrangement | Must hold |
|---|---|---|
| fnm in `.zshrc` only | Node 22 in login shells; none in non-interactive shells or GUI apps | git and tarball updates complete; setup **warns** for the non-interactive shell and GUI apps, with fnm/`.zshenv` advice; doctor rows match |
| fnm in `.zshenv` | Node 22 in every shell; none for GUI apps | updates complete; only the GUI apps row warns |
| Node 20 on PATH | the field machine | git update completes **and builds `mcp/dist`**; the update warns up front; setup warns "below 22"; exit 0 |
| No Node anywhere, tarball | a user who never installed Node | update and setup complete (setup declines the Homebrew offer, since there's no TTY); the server starts; no build attempted |
| No Node anywhere, git | same, git install | the update reports "MCP build failed" clearly and exits non-zero, without a traceback; the source has moved; `quern setup` after installing Node finishes it |
| MCP wrapper, Node 22 | tarball's `launcher.cjs` | answers the MCP handshake |
| MCP wrapper, Node 20 | same, with the cached Node 20 | the "requires Node >= 22" message, with the binary path; no syntax error |
| Unusual shell | `SHELL=/usr/local/bin/fish` | the shell rows read *unknown* with a reason, not *missing*; nothing blocks |

**One product change is needed first:** the updater and `install.sh` currently only talk to GitHub. One environment variable (e.g. `QUERN_RELEASES_URL`), read by both, lets the rehearsal serve the candidate locally. Nothing sets it in normal use.

### 2. Verification after publishing: `scripts/release-verify.sh vX.Y.Z`

Automated, about two minutes, against the real release:
- anonymous `releases/latest` = the new tag;
- the updater resolves stable and beta to it;
- `release/stable`, `release/beta`, `main` and the tag all point at one commit;
- the downloaded tarball has the version, `mcp/dist`, its `node_modules`, and a signed, notarized app of that version;
- the quern.dev update check offers it;
- a real tarball update from the previous published release to this one succeeds.

### 3. Real-machine smoke test (manual, about 5 minutes)

- Update the maintainer's git install through the beta channel, running `quern update` from another directory.
- Confirm the menu-bar app is still running, `quern doctor` looks right, and one device action works.
- For minor releases, first publish `-rc.1` as a prerelease and use it for a day.

## How it changes the release doc

- **Step 0:** becomes "notarize **and** rehearse". Nothing gets tagged unless both pass.
- **After step 6:** run `release-verify.sh`, then the smoke test.
- **Checklist:** the item added for 0.18.4 ("update into this release from the previous one") becomes "run the rehearsal".

## Order of work
1. `QUERN_RELEASES_URL` in the updater and `install.sh`, plus `release-verify.sh`.
2. `release-rehearsal.sh` with the two update cases.
3. The Node environment cases (they depend on #218).
4. Fresh install, GUI start, MCP wrapper and menu-bar cases.
5. `docs/release-channels.md`.

## Out of scope (for now)
- A CI matrix across old versions (decided against: about 15 users).
- Running the rehearsal on a schedule.
- Real devices in automation.

**Comment by jerimiah797** [comment]
## Addendum: Node install types

Each Node environment case above runs once per install type, not once in total. This table is the matrix.

| Install type | Where `node` lives | How it reaches PATH | Seen by GUI apps? | In the sandbox |
|---|---|---|---|---|
| Homebrew `node` | `/opt/homebrew/bin` or `/usr/local/bin` | `brew shellenv` in `.zprofile` | yes (the menu bar adds both) | the cached binary placed in a relocated prefix |
| Homebrew `node@22` | `…/opt/node@22/bin`, not linked | manual | **no** | relocated prefix |
| Official installer (nodejs.org) | `/usr/local/bin/node` | already on PATH | yes | relocated prefix |
| n | `/usr/local/bin/node` | already on PATH | yes | relocated prefix |
| nvm | `~/.nvm/versions/node/vX/bin` | `.zshrc`, often lazy-loaded | no | real install into the sandbox `HOME` |
| fnm | `~/.local/state/fnm_multishells/<pid>/…` | `fnm env` in `.zshrc` **or** `.zshenv` | no | real install; both placements |
| Volta | `~/.volta/bin` (shims) | `.zshrc` / `.zprofile` | no | real install |
| asdf | `~/.asdf/shims` | `.zshrc` | no | real install |
| mise | `~/.local/share/mise/shims` or activated per directory | `mise activate` in `.zshrc` | no; version may depend on the current directory | real install; shims and activate |

Recognised for advice but not rehearsed: nodenv, MacPorts (`/opt/local/bin`), Nix (`~/.nix-profile/bin`, `/run/current-system/sw/bin`), pnpm env (`~/Library/pnpm`). MCP clients that bundle their own Node can't be checked from outside.

**For each type, check:**
- the doctor row for each place;
- the upgrade command it suggests is that manager's own (`nvm install 22 && nvm alias default 22`, `asdf install nodejs 22`, `mise use -g node@22`, `volta install node@22`, `n 22`, the nodejs.org installer, `brew upgrade node`);
- the GUI advice never suggests a keg-only formula;
- for mise: the directory the probe runs from is stated, since the answer can depend on it.

**Prerequisites:**
- #218's `manager_of` / `fix_for` must recognise asdf, mise, n, the official installer, nodenv, MacPorts, Nix and pnpm. Today it knows only fnm, nvm, Volta and Homebrew, and falls back to `brew install node` for everything else.
- The probe's fixed GUI directories (`/opt/homebrew/bin`, `/usr/local/bin`, …) need a test-only root override, so the system-location types can be recreated inside a sandbox rather than only on a real machine.

**Comment by jerimiah797** [comment]
## Where this stands, and cases we did not know to plan for

PR #229 implements layer 1 (`scripts/release-rehearsal.sh`) and layer 2 (`scripts/release-verify.sh`), plus the `QUERN_RELEASES_URL` change they depend on.

### Done

| Case | Notes |
|---|---|
| Git update, previous release's updater | Proven by reproduction: `release-rehearsal.sh v0.18.3 v0.18.2` still fails four checks with #212's `ImportError: cannot import name 'quern_cmd'` |
| GUI-style start | `env -i` with launchd's PATH; asserts `/health` answers rather than that a process appeared |
| Fresh install | Site repo's `install.sh` against a locally served candidate, then the wrapper run from another directory |
| MCP wrapper, Node 22 | Answers `initialize` |
| Node arrangements | `.zshrc` only, `.zshenv`, Node 20, no node, unsupported shell — asserted on the `doctor` rows, which are the product |
| Everything in layer 2 | Plus skips that name what they could not check, so a skipped run cannot read as a clean one |

### Still owed from the plan above

- **No node anywhere, git** and **no node anywhere, tarball** — the two error paths, with four separate claims each and nothing checking any of them.
- **Node 20 during an update** — the matrix asserts what `doctor` *says* about Node 20, not that an update on it completes and still builds `mcp/dist`. Saying "too old" and failing to build are different failures.
- **The MCP wrapper on a real Node 20** — the matrix uses a shim that answers `--version`, which proves visibility but not behaviour. The wrapper's own refusal needs a real old binary, fetched and cached once.
- **The menu-bar step (#215).**
- **Tarball update** — blocked, not missing. It needs the *previous* release to honour `QUERN_RELEASES_URL`, so it can first run when updating from 0.18.5. Declared and skipped with that reason until then.

### New cases, learned after this issue was written

Each maps to a defect that has actually shipped or to a path the recent work created.

| Case | Must hold | Why |
|---|---|---|
| **Update while the server is running** | The daemon is restarted and healthy afterwards | Every case today updates with the daemon stopped. Real users don't, and "the server doesn't come back" is the whole premise of #225/#226. The highest-value gap. |
| **Downgrade refusal** | An older candidate is refused, `Not downgrading` is printed, and the exit code is not rc 2 | 0.18.1's shipped defect. Layer 2 checks what a channel *resolves to* after publishing; nothing exercises the guard that refuses to act on a bad answer. |
| **Git install on a non-release branch** | It refuses to pull and says which branch to switch to | The common dev-clone state (#40), and that message has been wrong before. |
| **Local changes block the pull** | The "commit or stash first" message, not a raw git error | One stray edit is all it takes. |
| **Update with the menu-bar app running** | The app is quit and restored, or left alone with a reason | Where the destructive install swap lived. |
| **MCP registrations after an update** | The sandbox's registration points at the right path | Setup rewrites other tools' config, and this project has twice written the *wrong* path into `~/.claude/settings.json`. |

Suggested order when we pick this up: server-running update, downgrade refusal, no-node-git. Those three map to shipped defects. The real Node 20 binary and the menu-bar cases are more setup cost for less return.
